# Generated by Django 4.2.2 on 2023-10-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
