# Generated by Django 4.2.2 on 2023-10-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Views',
            field=models.IntegerField(default=None),
        ),
    ]
