# Generated by Django 4.2.2 on 2023-10-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0005_alter_mymodelfirst_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Comments_Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Count_Negative_Reactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Count_Positive_Reactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Reposts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
