# Generated by Django 4.2.2 on 2023-10-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0006_alter_mymodelfirst_comments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
