# Generated by Django 4.2.2 on 2023-10-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0007_alter_mymodelfirst_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Comment_Text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
