# Generated by Django 4.2.2 on 2023-10-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0008_alter_mymodelfirst_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Garbage',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Healthcare',
            field=models.BooleanField(null=True),
        ),
    ]
