# Generated by Django 4.2.2 on 2023-10-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0009_alter_mymodelfirst_garbage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Availability_of_Goods_and_Services',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Culture',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Education',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Environmental_Conditions',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Facts',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Housing_and_Public_Utilities',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Infrastructure',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Negative',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Neutral',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Official_Statements',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Politics',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Positive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Safety',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Social_Security',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Tourism',
            field=models.BooleanField(null=True),
        ),
    ]
