# Generated by Django 4.2.2 on 2023-11-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0010_alter_mymodelfirst_availability_of_goods_and_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Header',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
