# Generated by Django 4.2.2 on 2023-11-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0011_alter_mymodelfirst_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodelfirst',
            name='Text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
