# Generated by Django 4.2.2 on 2023-11-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0015_remove_profile_slug_remove_profile_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodelfirst',
            name='Count_Ton',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
