# Generated by Django 4.2.2 on 2023-11-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0017_remove_mymodelfirst_count_ton'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodelfirst',
            name='Count_Ton',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
