# Generated by Django 4.2.2 on 2023-11-17 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labeling', '0018_mymodelfirst_count_ton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodelfirst',
            name='Count_Ton',
        ),
    ]
